In [269]:
import pandas as pd

In [270]:
data = pd.read_csv("twitter_training.csv")

In [271]:
data = data.sample(15000, random_state = 42)

In [272]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
7757,9333,Overwatch,Positive,i can play overwatch again (bad)
3887,1872,CallOfDutyBlackopsColdWar,Negative,The base weapons of black ops Cold War are so ...
22629,4275,CS-GO,Neutral,Don'don t just jump me... @CSGO... is medal. t...
66836,7044,johnson&johnson,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434,11284,TomClancysRainbowSix,Positive,New video later shoot premiere at 12 and its g...

In [273]:
data = data.dropna()

In [274]:
data.drop_duplicates(inplace = True)

In [275]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
7757,9333,Overwatch,Positive,i can play overwatch again (bad)
3887,1872,CallOfDutyBlackopsColdWar,Negative,The base weapons of black ops Cold War are so ...
22629,4275,CS-GO,Neutral,Don'don t just jump me... @CSGO... is medal. t...
66836,7044,johnson&johnson,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434,11284,TomClancysRainbowSix,Positive,New video later shoot premiere at 12 and its g...

In [276]:
data.drop(columns = ['2401', 'Borderlands'], inplace = True)

In [277]:
data.rename(columns = ({'Positive': 'Sentiment', 'im getting on borderlands and i will murder you all ,': 'Tweets'}), inplace = True)

In [278]:
data = data.dropna(subset=['Tweets'])

In [279]:
data

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
7757     Positive                   i can play overwatch again (bad)
3887     Negative  The base weapons of black ops Cold War are so ...
22629     Neutral  Don'don t just jump me... @CSGO... is medal. t...
66836  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434    Positive  New video later shoot premiere at 12 and its g...

[14746 rows x 2 columns]

In [280]:
data = data[(data['Sentiment'] == 'Positive') | (data['Sentiment'] == 'Negative') | (data['Sentiment'] == 'Neutral')]

In [281]:
data

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...
...         ...                                                ...
57537  Positive  This is not my nice way of saying what GN with...
7757   Positive                   i can play overwatch again (bad)
3887   Negative  The base weapons of black ops Cold War are so ...
22629   Neutral  Don'don t just jump me... @CSGO... is medal. t...
56434  Positive  New video later shoot premiere at 12 and its g...

[12127 rows x 2 columns]

In [282]:
from sklearn.preprocessing import LabelEncoder

In [283]:
label = LabelEncoder()

In [284]:
data['Sentiment'] = label.fit_transform(data['Sentiment'])

In [285]:
data

       Sentiment                                             Tweets
21704          2         Yo this looks LIT! Team:GO/Overwatch combo
47008          0  Pay attention executive administrators. While ...
454            2                                                one
58076          0       @Rainbow6Game Server are Available in Xbox 🥺
40659          2  so Awesome siege attempt... strangest bleeding...
...          ...                                                ...
57537          2  This is not my nice way of saying what GN with...
7757           2                   i can play overwatch again (bad)
3887           0  The base weapons of black ops Cold War are so ...
22629          1  Don'don t just jump me... @CSGO... is medal. t...
56434          2  New video later shoot premiere at 12 and its g...

[12127 rows x 2 columns]

In [286]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [287]:
tokenizer = Tokenizer(oov_token = 'Nothing')
tokenizer.fit_on_texts(data['Tweets'])

In [288]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'this': 11,
 'it': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'have': 21,
 'be': 22,
 'just': 23,
 'me': 24,
 'not': 25,
 'but': 26,
 'are': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 '2': 31,
 'out': 32,
 'like': 33,
 'pic': 34,
 'twitter': 35,
 'your': 36,
 'from': 37,
 'get': 38,
 'now': 39,
 'as': 40,
 'we': 41,
 'good': 42,
 't': 43,
 'play': 44,
 'johnson': 45,
 'they': 46,
 'do': 47,
 'about': 48,
 'if': 49,
 'can': 50,
 'new': 51,
 'one': 52,
 'has': 53,
 'an': 54,
 'no': 55,
 'really': 56,
 'when': 57,
 "i'm": 58,
 'will': 59,
 'love': 60,
 'time': 61,
 'what': 62,
 'up': 63,
 'more': 64,
 'unk': 65,
 '3': 66,
 'some': 67,
 'why': 68,
 'still': 69,
 'shit': 70,
 'people': 71,
 "it's": 72,
 'or': 73,
 'co': 74,
 'by': 75,
 'been': 76,
 'how': 77,
 'https': 78,
 'amazon': 79,
 '’': 80,
 'microsoft': 81,
 'best': 82,
 'games': 83,
 'dead': 84,
 '1': 85,
 'facebook': 86,
 'fucking': 87,
 'playing': 88,
 'got': 89,
 'verizon': 90,
 'because': 91,
 'great': 92,
 'fuck': 93,
 'rhandlerr': 94,
 'go': 95,
 'red': 96,
 'even': 97,
 'please': 98,
 'xbox': 99,
 'who': 100,
 'see': 101,
 'them': 102,
 'us': 103,
 'home': 104,
 'back': 105,
 'much': 106,
 '5': 107,
 'only': 108,
 'google': 109,
 'going': 110,
 'there': 111,
 'had': 112,
 'am': 113,
 "can't": 114,
 'fix': 115,
 'nvidia': 116,
 's': 117,
 'borderlands': 118,
 'tv': 119,
 'would': 120,
 'their': 121,
 'after': 122,
 'fun': 123,
 'our': 124,
 '4': 125,
 'its': 126,
 'again': 127,
 'these': 128,
 'day': 129,
 'eamaddennfl': 130,
 'first': 131,
 'most': 132,
 'than': 133,
 'very': 134,
 'over': 135,
 "don't": 136,
 'fifa': 137,
 'wait': 138,
 'today': 139,
 'also': 140,
 'make': 141,
 'never': 142,
 '2020': 143,
 'here': 144,
 'pubg': 145,
 'redemption': 146,
 'then': 147,
 'twitch': 148,
 'know': 149,
 'nba2k': 150,
 'want': 151,
 'bad': 152,
 'ever': 153,
 'rainbow6game': 154,
 'think': 155,
 'thank': 156,
 'gta': 157,
 '…': 158,
 'he': 159,
 'amazing': 160,
 'every': 161,
 'damn': 162,
 'depot': 163,
 'work': 164,
 'year': 165,
 'ps5': 166,
 'played': 167,
 'thanks': 168,
 'legends': 169,
 'video': 170,
 'guys': 171,
 'x': 172,
 'getting': 173,
 'call': 174,
 'i’m': 175,
 'too': 176,
 'last': 177,
 'news': 178,
 'series': 179,
 'help': 180,
 "i've": 181,
 'any': 182,
 'world': 183,
 'warcraft': 184,
 'happy': 185,
 'down': 186,
 'into': 187,
 'well': 188,
 '10': 189,
 'while': 190,
 'black': 191,
 'league': 192,
 'v': 193,
 'being': 194,
 'years': 195,
 'u': 196,
 'overwatch': 197,
 'off': 198,
 'man': 199,
 'watch': 200,
 'looks': 201,
 'say': 202,
 'always': 203,
 'right': 204,
 'youtu': 205,
 'another': 206,
 'ghostrecon': 207,
 'live': 208,
 'did': 209,
 'finally': 210,
 'creed': 211,
 'stop': 212,
 'update': 213,
 'need': 214,
 'team': 215,
 'youtube': 216,
 'store': 217,
 'battlefield': 218,
 'actually': 219,
 'players': 220,
 'should': 221,
 'everyone': 222,
 'ass': 223,
 'via': 224,
 'money': 225,
 'made': 226,
 'his': 227,
 'look': 228,
 'next': 229,
 'fortnite': 230,
 'buy': 231,
 'csgo': 232,
 'way': 233,
 'big': 234,
 'hearthstone': 235,
 'win': 236,
 'duty': 237,
 'already': 238,
 'many': 239,
 'free': 240,
 'thing': 241,
 'better': 242,
 'could': 243,
 'which': 244,
 'take': 245,
 'since': 246,
 'playstation': 247,
 'were': 248,
 'come': 249,
 'health': 250,
 'awesome': 251,
 'wow': 252,
 'wtf': 253,
 'it’s': 254,
 'before': 255,
 'support': 256,
 'same': 257,
 'access': 258,
 'nice': 259,
 'something': 260,
 'bit': 261,
 'care': 262,
 'pc': 263,
 'hate': 264,
 'keep': 265,
 'such': 266,
 'her': 267,
 'playapex': 268,
 'other': 269,
 'online': 270,
 'done': 271,
 'gonna': 272,
 'trying': 273,
 'excited': 274,
 '20': 275,
 'having': 276,
 'ubisoft': 277,
 'ly': 278,
 'days': 279,
 'give': 280,
 'oh': 281,
 'stream': 282,
 '100': 283,
 'hey': 284,
 'baby': 285,
 'everything': 286,
 'pretty': 287,
 'both': 288,
 '6': 289,
 'cool': 290,
 'lot': 291,
 'looking': 292,
 'old': 293,
 'war': 294,
 'doing': 295,
 'long': 296,
 'check': 297,
 'account': 298,
 'does': 299,
 'where': 300,
 'top': 301,
 'start': 302,
 'life': 303,
 'im': 304,
 'someone': 305,
 'mobile': 306,
 'cyberpunk': 307,
 'through': 308,
 'card': 309,
 'nothing': 310,
 '7': 311,
 'pay': 312,
 'two': 313,
 'player': 314,
 'real': 315,
 'use': 316,
 'things': 317,
 'servers': 318,
 'him': 319,
 'powder': 320,
 'feel': 321,
 'dota': 322,
 'super': 323,
 'lol': 324,
 'working': 325,
 'phone': 326,
 'stupid': 327,
 'little': 328,
 'night': 329,
 'm': 330,
 'hope': 331,
 'those': 332,
 'service': 333,
 'problem': 334,
 'making': 335,
 'company': 336,
 'season': 337,
 'god': 338,
 'hours': 339,
 'almost': 340,
 'hell': 341,
 'makes': 342,
 'ops': 343,
 'yet': 344,
 'literally': 345,
 'until': 346,
 'week': 347,
 '2077': 348,
 'italy': 349,
 'probably': 350,
 'anyone': 351,
 'dont': 352,
 'miss': 353,
 'favorite': 354,
 'can’t': 355,
 '19': 356,
 'uk': 357,
 'cold': 358,
 'against': 359,
 'won': 360,
 'try': 361,
 'business': 362,
 'hard': 363,
 'release': 364,
 "doesn't": 365,
 'whole': 366,
 'absolutely': 367,
 'let': 368,
 'full': 369,
 'own': 370,
 'find': 371,
 'times': 372,
 'worst': 373,
 'gaming': 374,
 'lost': 375,
 'show': 376,
 'chance': 377,
 'trash': 378,
 'said': 379,
 'app': 380,
 'minutes': 381,
 'few': 382,
 'apex': 383,
 'fact': 384,
 'open': 385,
 '0': 386,
 'end': 387,
 'put': 388,
 'says': 389,
 'without': 390,
 'part': 391,
 'story': 392,
 'cant': 393,
 "that's": 394,
 'assassins': 395,
 'hit': 396,
 '2k': 397,
 'mode': 398,
 'interesting': 399,
 'stuff': 400,
 'far': 401,
 'console': 402,
 'using': 403,
 'ea': 404,
 'guy': 405,
 'sure': 406,
 'coming': 407,
 'ranked': 408,
 'wrong': 409,
 'gameplay': 410,
 'idea': 411,
 'ps4': 412,
 'callofduty': 413,
 'anything': 414,
 'gets': 415,
 'ban': 416,
 'tt': 417,
 'around': 418,
 'thought': 419,
 'maybe': 420,
 'order': 421,
 'selling': 422,
 'vaccine': 423,
 'data': 424,
 '30': 425,
 'reason': 426,
 'tell': 427,
 'friends': 428,
 '21': 429,
 'screen': 430,
 "you're": 431,
 'beautiful': 432,
 'perfect': 433,
 'million': 434,
 'soon': 435,
 'crazy': 436,
 'worth': 437,
 'enough': 438,
 '15': 439,
 'used': 440,
 'y’all': 441,
 'd': 442,
 'covid': 443,
 "y'all": 444,
 'sad': 445,
 'point': 446,
 'pro': 447,
 'madden': 448,
 'though': 449,
 'enjoy': 450,
 'tonight': 451,
 'w': 452,
 'p': 453,
 'bought': 454,
 'high': 455,
 'dota2': 456,
 'graphics': 457,
 'line': 458,
 'currently': 459,
 'went': 460,
 'talc': 461,
 "didn't": 462,
 'away': 463,
 'banned': 464,
 'watching': 465,
 'month': 466,
 'change': 467,
 'weekend': 468,
 'epic': 469,
 'may': 470,
 'system': 471,
 'forward': 472,
 'internet': 473,
 'second': 474,
 '12': 475,
 'playhearthstone': 476,
 'tried': 477,
 'ift': 478,
 'different': 479,
 'bro': 480,
 'feels': 481,
 'kill': 482,
 "i'll": 483,
 "assassin's": 484,
 'due': 485,
 'price': 486,
 'share': 487,
 'broken': 488,
 'based': 489,
 'latest': 490,
 'saying': 491,
 'grand': 492,
 'org': 493,
 'services': 494,
 'cause': 495,
 '”': 496,
 'able': 497,
 'job': 498,
 'don’t': 499,
 'ok': 500,
 'cs': 501,
 'pre': 502,
 'patch': 503,
 'took': 504,
 'comes': 505,
 'skin': 506,
 'character': 507,
 'definitely': 508,
 'ago': 509,
 'morning': 510,
 'server': 511,
 'mean': 512,
 'myself': 513,
 'homedepot': 514,
 'exciting': 515,
 'sorry': 516,
 'power': 517,
 'else': 518,
 'huge': 519,
 'terrible': 520,
 'myteam': 521,
 'wanna': 522,
 'n2k': 523,
 'instead': 524,
 'might': 525,
 'problems': 526,
 'despite': 527,
 'cod': 528,
 'level': 529,
 'post': 530,
 'came': 531,
 'sucks': 532,
 'gold': 533,
 'i’ve': 534,
 'started': 535,
 'beluba': 536,
 'must': 537,
 'net': 538,
 'apps': 539,
 'cards': 540,
 'read': 541,
 'rewards': 542,
 'content': 543,
 'finished': 544,
 'customer': 545,
 'anymore': 546,
 'products': 547,
 'she': 548,
 'wanted': 549,
 'windows': 550,
 'eu': 551,
 'during': 552,
 'guess': 553,
 'music': 554,
 '8': 555,
 'seems': 556,
 'event': 557,
 'leagueoflegends': 558,
 'updates': 559,
 'months': 560,
 'luck': 561,
 'ready': 562,
 'seen': 563,
 'needs': 564,
 'killed': 565,
 'tomorrow': 566,
 'achievement': 567,
 'dlvr': 568,
 'set': 569,
 '9': 570,
 'run': 571,
 'match': 572,
 'y': 573,
 'trailer': 574,
 'annoying': 575,
 'experience': 576,
 'later': 577,
 're': 578,
 'talk': 579,
 'remember': 580,
 'single': 581,
 "won't": 582,
 'r': 583,
 'die': 584,
 'holy': 585,
 'shot': 586,
 'seriously': 587,
 'name': 588,
 'error': 589,
 'list': 590,
 'design': 591,
 'ronnie2k': 592,
 'early': 593,
 'breakpoint': 594,
 'half': 595,
 '3080': 596,
 'hi': 597,
 'yo': 598,
 'hour': 599,
 'taken': 600,
 'step': 601,
 'living': 602,
 'yall': 603,
 'honestly': 604,
 'least': 605,
 'gone': 606,
 'rtx': 607,
 'three': 608,
 'found': 609,
 'edition': 610,
 "haven't": 611,
 'buying': 612,
 'number': 613,
 'completely': 614,
 'face': 615,
 'loved': 616,
 'warzone': 617,
 'earned': 618,
 'place': 619,
 'blizzard': 620,
 'sometimes': 621,
 'late': 622,
 'gen': 623,
 'easports': 624,
 'once': 625,
 'community': 626,
 'person': 627,
 'c': 628,
 'yes': 629,
 'e': 630,
 'videos': 631,
 'proud': 632,
 'believe': 633,
 'issue': 634,
 'don': 635,
 'book': 636,
 'class': 637,
 '•': 638,
 'issues': 639,
 'below': 640,
 'apple': 641,
 'together': 642,
 'hear': 643,
 'seeing': 644,
 'funny': 645,
 'teams': 646,
 'totally': 647,
 'small': 648,
 'called': 649,
 'movie': 650,
 'friend': 651,
 'keeps': 652,
 'fan': 653,
 'omg': 654,
 'birthday': 655,
 'pass': 656,
 'thinking': 657,
 'suck': 658,
 'bullshit': 659,
 'each': 660,
 'follow': 661,
 'code': 662,
 'city': 663,
 'hello': 664,
 'worse': 665,
 'ghost': 666,
 'review': 667,
 'complete': 668,
 'smh': 669,
 'less': 670,
 'kinda': 671,
 'major': 672,
 'released': 673,
 'retweet': 674,
 'under': 675,
 'sound': 676,
 'trump': 677,
 'switch': 678,
 'sick': 679,
 'canada': 680,
 'battle': 681,
 'leave': 682,
 'past': 683,
 'streaming': 684,
 'either': 685,
 'tech': 686,
 'bugs': 687,
 'understand': 688,
 'launch': 689,
 'incredible': 690,
 'join': 691,
 'india': 692,
 'tired': 693,
 'main': 694,
 "they're": 695,
 'daily': 696,
 'gotta': 697,
 '“': 698,
 'article': 699,
 'lmao': 700,
 'kills': 701,
 'running': 702,
 'cannot': 703,
 'link': 704,
 'yesterday': 705,
 'saw': 706,
 'odyssey': 707,
 'ai': 708,
 'action': 709,
 'instagram': 710,
 'deal': 711,
 'add': 712,
 'move': 713,
 'cute': 714,
 'received': 715,
 'bring': 716,
 'stock': 717,
 'gift': 718,
 'mind': 719,
 'joke': 720,
 'iphone': 721,
 'b': 722,
 'family': 723,
 'market': 724,
 'waiting': 725,
 'garbage': 726,
 "we're": 727,
 'starting': 728,
 'kind': 729,
 'slow': 730,
 'mad': 731,
 'house': 732,
 've': 733,
 'stay': 734,
 'global': 735,
 "what's": 736,
 'ubisoftsupport': 737,
 'means': 738,
 "let's": 739,
 'drop': 740,
 'moment': 741,
 'girl': 742,
 'entire': 743,
 'franchise': 744,
 'that’s': 745,
 'goes': 746,
 'moments': 747,
 'fps': 748,
 'technology': 749,
 'truly': 750,
 'playoverwatch': 751,
 'points': 752,
 'absolute': 753,
 'glad': 754,
 'rockstargames': 755,
 'social': 756,
 'tho': 757,
 'spent': 758,
 'id': 759,
 'page': 760,
 'commission': 761,
 'quite': 762,
 'warfare': 763,
 'coronavirus': 764,
 'hyped': 765,
 'weeks': 766,
 'o': 767,
 'insane': 768,
 'bug': 769,
 'original': 770,
 'car': 771,
 '14': 772,
 'ur': 773,
 'steam': 774,
 'history': 775,
 'cancer': 776,
 'special': 777,
 'item': 778,
 'left': 779,
 'users': 780,
 'hot': 781,
 'trust': 782,
 'sounds': 783,
 'sell': 784,
 '–': 785,
 'continue': 786,
 'j': 787,
 'close': 788,
 'okay': 789,
 'congratulations': 790,
 'decided': 791,
 'boy': 792,
 'easy': 793,
 'delayed': 794,
 'talking': 795,
 'break': 796,
 'final': 797,
 'fortnitegame': 798,
 'taking': 799,
 'toxic': 800,
 'pick': 801,
 'version': 802,
 'star': 803,
 'lots': 804,
 'walmart': 805,
 'women': 806,
 'sold': 807,
 'takes': 808,
 'wikipedia': 809,
 'turn': 810,
 'dear': 811,
 'crap': 812,
 'yeah': 813,
 'sony': 814,
 "there's": 815,
 'happened': 816,
 'kids': 817,
 'siege': 818,
 'welcome': 819,
 'decision': 820,
 'en': 821,
 'hero': 822,
 'poverty': 823,
 'ridiculous': 824,
 'modern': 825,
 'including': 826,
 'men': 827,
 'paid': 828,
 'knows': 829,
 'performance': 830,
 'told': 831,
 '99': 832,
 'enjoyed': 833,
 '24': 834,
 'redeeming': 835,
 'fans': 836,
 'connection': 837,
 'shooting': 838,
 'wins': 839,
 'digital': 840,
 'report': 841,
 'worked': 842,
 'safe': 843,
 'mut': 844,
 'bitch': 845,
 'l': 846,
 'date': 847,
 'head': 848,
 'massive': 849,
 'feeling': 850,
 'plus': 851,
 'geforce': 852,
 'true': 853,
 'packs': 854,
 'works': 855,
 'box': 856,
 'wild': 857,
 'forever': 858,
 'heart': 859,
 'death': 860,
 'biggest': 861,
 'f': 862,
 'security': 863,
 'nba': 864,
 'shut': 865,
 'yourself': 866,
 'low': 867,
 'longer': 868,
 'died': 869,
 'dope': 870,
 'sense': 871,
 'beta': 872,
 'created': 873,
 'fight': 874,
 'stuck': 875,
 'fast': 876,
 'test': 877,
 'stopped': 878,
 'felt': 879,
 'china': 880,
 'channel': 881,
 'plan': 882,
 'boring': 883,
 'art': 884,
 'plz': 885,
 '11': 886,
 'state': 887,
 'gpu': 888,
 'unit': 889,
 'nfl': 890,
 'school': 891,
 'n': 892,
 'search': 893,
 'learning': 894,
 'listen': 895,
 'ordered': 896,
 'important': 897,
 'drive': 898,
 'sweet': 899,
 'hand': 900,
 'hold': 901,
 'somehow': 902,
 'plays': 903,
 'skins': 904,
 'platform': 905,
 'delivery': 906,
 'heard': 907,
 'current': 908,
 'email': 909,
 'option': 910,
 'developers': 911,
 'between': 912,
 'football': 913,
 '13': 914,
 'till': 915,
 'matter': 916,
 'cry': 917,
 'powerful': 918,
 'map': 919,
 'lose': 920,
 'enjoying': 921,
 'spend': 922,
 'rather': 923,
 'wish': 924,
 'future': 925,
 'crashing': 926,
 'ya': 927,
 '000': 928,
 'valorant': 929,
 'racist': 930,
 '60': 931,
 'rt': 932,
 'summoners': 933,
 'word': 934,
 'demon': 935,
 'favourite': 936,
 'pls': 937,
 'fixed': 938,
 'controller': 939,
 'quit': 940,
 'bc': 941,
 'recon': 942,
 'rest': 943,
 'log': 944,
 'couple': 945,
 'chinese': 946,
 'tf': 947,
 'giving': 948,
 'government': 949,
 '50': 950,
 'inside': 951,
 'ppl': 952,
 'eahelp': 953,
 'dark': 954,
 'behind': 955,
 'calling': 956,
 'theft': 957,
 '25': 958,
 'calls': 959,
 '16': 960,
 'trial': 961,
 'especially': 962,
 'companies': 963,
 'greatest': 964,
 'within': 965,
 'website': 966,
 'random': 967,
 'white': 968,
 'brand': 969,
 'sales': 970,
 'suddenly': 971,
 'imagine': 972,
 'fantastic': 973,
 'control': 974,
 'party': 975,
 'program': 976,
 'gave': 977,
 'fake': 978,
 'cuz': 979,
 'towards': 980,
 'king': 981,
 'decent': 982,
 'edge': 983,
 'quality': 984,
 'tweet': 985,
 'shitty': 986,
 'ahead': 987,
 'pandemic': 988,
 'short': 989,
 'monday': 990,
 'create': 991,
 'customers': 992,
 'ball': 993,
 'happens': 994,
 "isn't": 995,
 'features': 996,
 'explain': 997,
 'af': 998,
 'dumb': 999,
 'finish': 1000,
 ...}

In [289]:
tokenizer.word_counts

OrderedDict([('yo', 51),
             ('this', 2399),
             ('looks', 180),
             ('lit', 14),
             ('team', 167),
             ('go', 353),
             ('overwatch', 182),
             ('combo', 8),
             ('pay', 112),
             ('attention', 10),
             ('executive', 4),
             ('administrators', 4),
             ('while', 188),
             ('your', 724),
             ('stores', 26),
             ('are', 945),
             ('taking', 35),
             ('delivery', 30),
             ('orders', 19),
             ('for', 2543),
             ('pallets', 2),
             ('of', 3209),
             ('bricks', 2),
             ('to', 4802),
             ('downtown', 2),
             ('then', 243),
             ('you', 1923),
             ('were', 145),
             ('being', 185),
             ('used', 72),
             ('in', 2564),
             ('helping', 24),
             ('the', 7261),
             ('destruction', 5),
             ('private', 10),
             ('property', 6),
             ('one', 556),
             ('rainbow6game', 231),
             ('server', 61),
             ('available', 26),
             ('xbox', 344),
             ('🥺', 9),
             ('so', 1273),
             ('awesome', 143),
             ('siege', 34),
             ('attempt', 6),
             ('strangest', 3),
             ('bleeding', 4),
             ('out', 746),
             ('spinning', 8),
             ('sequence', 2),
             ('ever', 232),
             ('s', 293),
             ('my', 2015),
             ('first', 268),
             ('squadmate', 1),
             ('john', 14),
             ('could', 151),
             ('see', 334),
             ('exactly', 16),
             ('which', 151),
             ('was', 922),
             ("i'm", 524),
             ('really', 528),
             ('looking', 122),
             ('forward', 67),
             ('game', 1503),
             ('verizon', 366),
             ('sheds', 1),
             ('81', 4),
             ('000', 29),
             ('digital', 33),
             ('tv', 285),
             ('on', 1974),
             ('black', 188),
             ('cutting', 8),
             ('escalates', 1),
             ('breitbart', 2),
             ('com', 1586),
             ('entertainment', 13),
             ('internet', 67),
             ('gave', 27),
             ('way', 157),
             ('coke', 3),
             ('show', 87),
             ('money', 160),
             ('keep', 135),
             ('ch', 2),
             ('tmmobile', 1),
             ('guys', 209),
             ('very', 261),
             ('slow', 39),
             ('town', 12),
             ('tuba', 2),
             ('fix', 302),
             ('fucking', 374),
             ('pro', 71),
             ('am', 311),
             ('can’t', 96),
             ('find', 90),
             ('no', 532),
             ('games', 382),
             ('2ksupport', 22),
             ('i', 4932),
             ('love', 523),
             ('how', 440),
             ('gives', 20),
             ('each', 45),
             ('a', 3935),
             ('new', 568),
             ('loot', 22),
             ('box', 32),
             ('playing', 374),
             ('support', 139),
             ('forgot', 26),
             ('when', 528),
             ('hated', 7),
             ('who', 341),
             ('mad', 39),
             ('about', 580),
             ('dame', 10),
             ('getting', 208),
             ('itself', 23),
             ('regular', 9),
             ('cover', 16),
             ('like', 744),
             ('kobe', 8),
             ('or', 449),
             ('get', 689),
             ('its', 277),
             ('legend', 21),
             ('edition', 50),
             ('unk', 488),
             ('disrespect', 8),
             ('y’all', 72),
             ('showed', 17),
             ('wild', 32),
             ('simpletons', 1),
             ('only', 320),
             ('lol', 106),
             ("here's", 14),
             ('montage', 6),
             ('rescuing', 1),
             ('teammate', 14),
             ('spreadlovehxly', 2),
             ('few', 86),
             ('times', 90),
             ('other', 134),
             ('day', 273),
             ('they', 593),
             ('will', 524),
             ('forever', 32),
             ('be', 1132),
             ('heart', 32),
             ('but', 963),
             ('do', 593),
             ('kinda', 44),
             ('tho', 38),
             ('5', 321),
             ('friends', 74),
             ('players', 165),
             ('pokemon', 13),
             ('borderlands', 292),
             ('p', 70),
             ('much', 322),
             ('all', 936),
             ('sims', 5),
             ('6', 123),
             ("haven't", 50),
             ('played', 216),
             ('spiderman', 3),
             ('2', 751),
             ('reignited', 1),
             ('uuuh', 2),
             ("that'm", 1),
             ('not', 1046),
             ('through', 114),
             ('with', 1441),
             ('either', 43),
             ('ciaranstrange', 3),
             ('sasspiria', 1),
             ('playstation', 146),
             ('bleh', 2),
             ('holy', 52),
             ('shit', 458),
             ('what', 514),
             ('world', 198),
             ('we', 632),
             ('omg', 46),
             ('dreamcatcher', 1),
             ('x', 209),
             ('league', 188),
             ('federals', 1),
             ('cruises', 1),
             ('paybackindia', 2),
             ('50', 28),
             ('it', 2372),
             ('also', 250),
             ('received', 40),
             ('an', 538),
             ('amazon', 404),
             ('e', 48),
             ('voucher', 6),
             ('offering', 4),
             ('inr', 2),
             ('500', 15),
             ('as', 636),
             ('payback', 6),
             ('rewards', 57),
             ('if', 579),
             ('don’t', 63),
             ('come', 144),
             ('ain’t', 13),
             ('buying', 50),
             ('china', 31),
             ('closes\xa0foxconn', 1),
             ('johnson', 609),
             ('and', 4376),
             ('samsung', 20),
             ('factories', 8),
             ('amid', 10),
             ('virus', 23),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('2020', 246),
             ('01', 23),
             ('27', 7),
             ('chi…', 1),
             ('https', 407),
             ('t', 613),
             ('co', 449),
             ('cltmh7bc2m', 2),
             ('just', 1127),
             ('spent', 38),
             ('hour', 51),
             ('at', 828),
             ('home', 323),
             ('depot', 218),
             ('renovating', 1),
             ('house', 39),
             ('expensive', 21),
             ('hell', 100),
             ('closer', 6),
             ('birthday', 46),
             ('cool', 123),
             ('exhausted', 7),
             ('from', 718),
             ('work', 218),
             ('week', 99),
             ('probably', 98),
             ('stream', 127),
             ('today', 251),
             ('i’m', 206),
             ('stoked', 4),
             ('ok', 63),
             ('dont', 97),
             ('care', 136),
             ('charge', 14),
             ('me', 1111),
             ('70', 26),
             ('too', 206),
             ('toxic', 35),
             ('masculinity', 4),
             ('sent', 26),
             ('specifically', 1),
             ('searching', 9),
             ('“men’s', 2),
             ('hair', 16),
             ('again', 276),
             ('d', 72),
             ('mean', 61),
             ('midterms', 2),
             ('because', 363),
             ('it’s', 140),
             ('late', 49),
             ('tired', 42),
             ('atvi', 3),
             ('update', 170),
             ('their', 284),
             ('most', 268),
             ('popular', 7),
             ('hearthstone', 156),
             ('is', 2893),
             ('investors', 11),
             ('should', 163),
             ('satisfied', 7),
             ('amount', 19),
             ('things', 110),
             ('company', 101),
             ('doing', 121),
             ('make', 250),
             ('more', 501),
             ('every', 221),
             ('happy', 194),
             ('enthusiastic', 4),
             ('jerseyboys', 1),
             ('now', 682),
             ('represented', 1),
             ('fb', 15),
             ('welcome', 34),
             ('chucky', 1),
             ('csgo', 158),
             ('our', 278),
             ('chef', 1),
             ('offer', 23),
             ('content', 57),
             ('various', 6),
             ('such', 135),
             ('warcraft', 197),
             ('cs', 63),
             ('valorant', 29),
             ('click', 26),
             ('here', 244),
             ('channel', 31),
             ('tinyurl', 12),
             ('y5gm9h74', 1),
             ('«', 9),
             ('weapon', 19),
             ('development', 9),
             ('sunsetting', 1),
             ('systems', 11),
             ('best', 387),
             ('news', 204),
             ("i've", 201),
             ('heard', 30),
             ('long', 121),
             ('time', 519),
             ('those', 103),
             ('that', 1715),
             ('play', 611),
             ('any', 200),
             ('multi', 4),
             ('major', 44),
             ('season', 101),
             ('strategy', 7),
             ('plan', 31),
             ('involved', 6),
             ('know', 240),
             ('transformation', 1),
             ('needed', 25),
             ('can', 573),
             ('relate', 2),
             ('glorious', 5),
             ('days', 129),
             ('mtg', 5),
             ('bring', 40),
             ('versatile', 3),
             ('creative', 8),
             ('builds', 1),
             ('problems', 59),
             ('sexual', 4),
             ('assaults', 1),
             ('educational', 3),
             ('institutions', 1),
             ('pia', 1),
             ('fake', 27),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 19),
             ('arrested', 3),
             ('protested', 1),
             ('against', 95),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 9),
             ('cases', 5),
             ('rising', 7),
             ('christian', 2),
             ('man', 181),
             ('shot', 52),
             ('he', 224),
             ('had', 318),
             ('bought', 70),
             ('muslim', 2),
             ('majority', 2),
             ('steps', 8),
             ('taken', 51),
             ('ban', 77),
             ('pubg', 244),
             ('3', 484),
             ('these', 274),
             ('even', 347),
             ('wore', 4),
             ('tannis', 2),
             ('her', 135),
             ('handsome', 8),
             ('jack', 10),
             ('want', 236),
             ('report', 33),
             ('racist', 29),
             ('uses', 8),
             ('vile', 2),
             ('words', 13),
             ('harass', 2),
             ('legends', 213),
             ("person's", 3),
             ('id', 38),
             ('gotcha', 2),
             ('uwu', 8),
             ('xd', 19),
             ('20', 131),
             ('series', 202),
             ('dlss', 1),
             ('0', 85),
             ('graphics', 69),
             ('processors', 2),
             ('run', 54),
             ('4k', 14),
             ('speeds', 15),
             ('than', 267),
             ('60', 29),
             ('frames', 4),
             ('per', 20),
             ('second', 67),
             ('according', 6),
             ('nvidia', 300),
             ('pcg', 1),
             ('au', 10),
             ('death', 32),
             ('stran', 1),
             ('why', 475),
             ('two', 112),
             ('year', 218),
             ('old', 122),
             ('them', 329),
             ('same', 139),
             ('youtube', 167),
             ('videos', 48),
             ('ten', 14),
             ('after', 279),
             ('bored', 12),
             ('assassins', 83),
             ('creed', 171),
             ('12', 67),
             ('great', 362),
             ('finished', 57),
             ('off', 182),
             ('last', 205),
             ('red', 350),
             ('dead', 382),
             ('redemption', 244),
             ('legendary', 22),
             ('animal', 17),
             ('pre', 63),
             ('epilogue', 2),
             ('good', 626),
             ('style', 7),
             ('pic', 741),
             ('twitter', 731),
             ('uyo0gbr2bd', 1),
             ('never', 248),
             ('miss', 97),
             ('follow', 45),
             ('current', 30),
             ('updates', 55),
             ('tech', 43),
             ('covid', 72),
             ('19', 96),
             ('comments', 17),
             ('etc', 20),
             ('exc', 1),
             ('playhearthstone', 67),
             ('legit', 14),
             ('disable', 10),
             ('djinn', 1),
             ('asap', 4),
             ('crony', 1),
             ('lame', 11),
             ('boring', 31),
             ('duvalmagic', 8),
             ('gearboxofficial', 23),
             ('wanted', 56),
             ('say', 180),
             ('saying', 64),
             ('huge', 60),
             ('thank', 227),
             ('worked', 33),
             ('working', 106),
             ('wheels', 3),
             ('gearbox', 7),
             ('’', 401),
             ('ve', 39),
             ('been', 443),
             ('crushing', 8),
             ('enven', 2),
             ('months', 55),
             ('before', 140),
             ('knowing', 17),
             ('must', 58),
             ('have', 1161),
             ('real', 111),
             ('difficult', 17),
             ('biggest', 32),
             ('fifa', 253),
             ('21', 74),
             ('downgrades', 1),
             ('⏬', 1),
             ('1', 381),
             ('collab', 2),
             ('f', 32),
             ('sebfut', 1),
             ('waht', 3),
             ('kill', 66),
             ('store', 167),
             ("it's", 456),
             ('five', 22),
             ('kid', 10),
             ('microsoft', 397),
             ('wants', 23),
             ('backwards', 5),
             ('compatible', 16),
             ('console', 81),
             ('mobilesyrup', 2),
             ('05', 20),
             ('28', 20),
             ('mic…', 3),
             ('�', 4),
             ('switched', 11),
             ('got', 371),
             ('galaxy', 6),
             ('note20', 1),
             ('ultra', 10),
             ('decision', 34),
             ('made', 160),
             ("y'all", 72),
             ("ain't", 9),
             ('help', 202),
             ('bokchoy', 1),
             ('request', 16),
             ('forget', 17),
             ('gonna', 133),
             ('google', 320),
             ('tube', 1),
             ('cook', 3),
             ('nasty', 10),
             ('kissing', 1),
             ('rt', 29),
             ('cragon', 1),
             ('myself', 61),
             ('dracula', 1),
             ('masquerade', 2),
             ('origins', 10),
             ('deus', 1),
             ('ex', 12),
             ('human', 21),
             ('revolution', 2),
             ('harry', 3),
             ('breath', 8),
             ('og', 9),
             ('leisure', 1),
             ('suit', 8),
             ('corps', 4),
             ("don't", 254),
             ('judge', 7),
             ('fluffbrawl', 1),
             ('killerxkween91', 1),
             ('itslexitaylor', 1),
             ('jbirdsgaming', 1),
             ('wtty', 1),
             ('gamewrexham', 2),
             ('gamedigital', 2),
             ('email', 30),
             ('stay', 39),
             ('safe', 33),
             ('thanks', 214),
             ('industry', 11),
             ('uk', 96),
             ('restart', 21),
             ('by', 444),
             ('9th', 4),
             ('gen', 49),
             ('still', 460),
             ('iffy', 2),
             ('malphite', 2),
             ('shard', 3),
             ('art', 31),
             ('war', 122),
             ('monolith', 2),
             ('always', 180),
             ('hard', 94),
             ('pick', 35),
             ('attack', 17),
             ('physical', 9),
             ('defense', 26),
             ('magic', 21),
             ('difficulty', 9),
             ('life', 116),
             ('give', 129),
             ('700', 5),
             ('bad', 233),
             ("can't", 307),
             ('dang', 12),
             ('thing', 153),
             ('stock', 40),
             ('plz', 31),
             ('bleepincomputer', 1),
             ('flash', 7),
             ('released', 44),
             ('security', 32),
             ("mysterious'spoofing", 1),
             ("virus'", 1),
             ('windows', 56),
             ('11', 31),
             ('tracked', 1),
             ('cve', 2),
             ('1464', 1),
             ('mention', 14),
             ('discovered', 10),
             ('version', 35),
             ('acknowledgement', 2),
             ('page', 38),
             ('ir', 1),
             ('msrc', 1),
             ('en', 34),
             ('us', 329),
             ('security…', 1),
             ('…', 225),
             ('youre', 7),
             ('throttling', 4),
             ('shame', 25),
             ('schooling', 2),
             ('people', 457),
             ('option', 30),
             ('nothing', 113),
             ("nvidia's", 14),
             ('shares', 11),
             ('rises', 5),
             ('toward', 3),
             ('record', 12),
             ('high', 70),
             ('bernstein', 1),
             ('turns', 13),
             ('bullish', 2),
             ('cuts', 3),
             ('price', 65),
             ('target', 18),
             ('mktw', 2),
             ('net', 58),
             ('32fx3km', 1),
             ('initial', 5),
             ('state', 31),
             ('alabama', 1),
             ('blank', 8),
             ('im', 116),
             ('wasting', 8),
             ('dota', 108),
             ('chick', 4),
             ('insane', 37),
             ('makes', 100),
             ('upgrade', 19),
             ('gpu', 31),
             ('video', 212),
             ('inside', 28),
             ('crashes', 25),
             ('would', 285),
             ('call', 207),
             ('videogamecrashception', 2),
             ('need', 170),
             ('leo', 4),
             ('youtu', 177),
             ('h9jup8kt9wu', 3),
             ('beautiful', 73),
             ('online', 134),
             ('order', 76),
             ('homedepot', 61),
             ('perfect', 73),
             ('→', 7),
             ('eljeeeey', 1),
             ('entering', 22),
             ('grand', 64),
             ('summoners', 29),
             ('watch', 181),
             ('won', 95),
             ('100', 126),
             ('gift', 40),
             ('card', 114),
             ('retweet', 44),
             ('everyday', 21),
             ('another', 176),
             ('chance', 87),
             ('win', 156),
             ('gs', 20),
             ('global', 39),
             ('free', 154),
             ('golden', 25),
             ('kamuy', 7),
             ('unit', 31),
             ('ylnbixjdii', 1),
             ('tile', 3),
             ('enjoyable', 9),
             ('wonderful', 19),
             ('hotel', 4),
             ('throughout', 12),
             ('madden', 71),
             ('nfl', 31),
             ('4', 278),
             ('ps4', 78),
             ('39', 6),
             ('95', 7),
             ('ebay', 21),

In [290]:
tokenizer.document_count

12127

In [291]:
len(tokenizer.word_index)

17872

In [292]:
sequences = tokenizer.texts_to_sequences(data['Tweets'])

In [293]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding = 'pre')

In [294]:
from tensorflow.keras.layers import SimpleRNN, Dense, Input, Embedding
from tensorflow.keras.models import Sequential

In [295]:
X = sequences
Y = data['Sentiment'].values

In [296]:
from sklearn.model_selection import train_test_split

In [297]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2,random_state=42)

In [298]:
model = Sequential()

In [299]:
model.add(SimpleRNN(32, input_shape = (99,1), return_sequences=False))
model.add(Dense(3, activation = 'softmax'))

d:\GenerativeAI\Project\TitanicDeepLearning\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [300]:
model.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'sparse_categorical_crossentropy')

In [301]:
model.fit(X_train, Y_train, epochs = 10, validation_data =(X_test, Y_test), batch_size=64)

Epoch 1/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3473 - loss: 1.1119 - val_accuracy: 0.3669 - val_loss: 1.0942
Epoch 2/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3614 - loss: 1.0924 - val_accuracy: 0.3578 - val_loss: 1.0946
Epoch 3/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3621 - loss: 1.0917 - val_accuracy: 0.3706 - val_loss: 1.0938
Epoch 4/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3676 - loss: 1.0905 - val_accuracy: 0.3619 - val_loss: 1.0899
Epoch 5/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3698 - loss: 1.0880 - val_accuracy: 0.3660 - val_loss: 1.0885
Epoch 6/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3694 - loss: 1.0865 - val_accuracy: 0.3611 - val_loss: 1.0921
Epoch 7/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3610 - loss: 1.0931 - val_accuracy: 0.3442 - val_loss: 1.0959
Epoch 8/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3625 - loss: 1.0914 - val_accuracy: 0.3607 - val_loss: 1.0923
Epoch 9/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3661 - loss: 1.0899 - val_accuracy: 0.3619 - val_loss: 1.0928
Epoch 10/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3651 - loss: 1.0896 - val_accuracy: 0.3442 - val_loss: 1.0974

In [302]:
vocab_size = len(tokenizer.word_index) + 1

In [305]:
model_2 = Sequential()
model_2.add(Input(shape=(99,)))
model_2.add(Embedding(input_dim = vocab_size, output_dim = 128))
model_2.add(Dense(3, activation = 'softmax'))

In [306]:
model_final = Sequential([Embedding(input_dim = vocab_size, output_dim = 128, input_length = 99, mask_zero = True), 
SimpleRNN(32),
Dense(3, activation = 'softmax')])

d:\GenerativeAI\Project\TitanicDeepLearning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [307]:
model_final.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'sparse_categorical_crossentropy')

In [308]:
model_final.fit(X_train, Y_train, epochs = 100, validation_data = (X_test, Y_test), batch_size = 64)

Epoch 1/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - accuracy: 0.5188 - loss: 0.9861 - val_accuracy: 0.6476 - val_loss: 0.8162
Epoch 2/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.8787 - loss: 0.3818 - val_accuracy: 0.6892 - val_loss: 0.7934
Epoch 3/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9626 - loss: 0.1180 - val_accuracy: 0.6900 - val_loss: 0.8685
Epoch 4/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9766 - loss: 0.0666 - val_accuracy: 0.6958 - val_loss: 0.9337
Epoch 5/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9791 - loss: 0.0508 - val_accuracy: 0.6941 - val_loss: 0.9917
Epoch 6/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9819 - loss: 0.0436 - val_accuracy: 0.6913 - val_loss: 1.0580
Epoch 7/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9814 - loss: 0.0412 - val_accuracy: 0.6834 - val_loss: 1.1350
Epoch 8/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9818 - loss: 0.0390 - val_accuracy: 0.6876 - val_loss: 1.1383
Epoch 9/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9810 - loss: 0.0387 - val_accuracy: 0.6917 - val_loss: 1.1532
Epoch 10/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9818 - loss: 0.0371 - val_accuracy: 0.6826 - val_loss: 1.2025
Epoch 11/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9810 - loss: 0.0363 - val_accuracy: 0.6962 - val_loss: 1.2041
Epoch 12/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9818 - loss: 0.0360 - val_accuracy: 0.7007 - val_loss: 1.2486
Epoch 13/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9814 - loss: 0.0355 - val_accuracy: 0.6933 - val_loss: 1.2683
Epoch 14/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9815 - loss: 0.0356 - val_accuracy: 0.6929 - val_loss: 1.2587
Epoch 15/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9815 - loss: 0.0351 - val_accuracy: 0.6822 - val_loss: 1.3041
Epoch 16/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9798 - loss: 0.0372 - val_accuracy: 0.6884 - val_loss: 1.3119
Epoch 17/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9813 - loss: 0.0349 - val_accuracy: 0.6805 - val_loss: 1.3649
Epoch 18/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9629 - loss: 0.0835 - val_accuracy: 0.6554 - val_loss: 1.3218
Epoch 19/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9648 - loss: 0.0866 - val_accuracy: 0.6760 - val_loss: 1.2268
Epoch 20/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9803 - loss: 0.0402 - val_accuracy: 0.6818 - val_loss: 1.2766
Epoch 21/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9806 - loss: 0.0360 - val_accuracy: 0.6822 - val_loss: 1.3143
Epoch 22/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9818 - loss: 0.0347 - val_accuracy: 0.6867 - val_loss: 1.3313
Epoch 23/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9801 - loss: 0.0345 - val_accuracy: 0.6843 - val_loss: 1.3513
Epoch 24/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9818 - loss: 0.0343 - val_accuracy: 0.6814 - val_loss: 1.3723
Epoch 25/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9814 - loss: 0.0347 - val_accuracy: 0.6838 - val_loss: 1.3853
Epoch 26/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9818 - loss: 0.0341 - val_accuracy: 0.6826 - val_loss: 1.3940
Epoch 27/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9812 - loss: 0.0343 - val_accuracy: 0.6834 - val_loss: 1.4120
Epoch 28/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9806 - loss: 0.0345 - val_accuracy: 0.6830 - val_loss: 1.4188
Epoch 29/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9811 - loss: 0.0340 - val_accuracy: 0.6855 - val_loss: 1.4202
Epoch 30/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9801 - loss: 0.0344 - val_accuracy: 0.6855 - val_loss: 1.4367
Epoch 31/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9817 - loss: 0.0339 - val_accuracy: 0.6851 - val_loss: 1.4373
Epoch 32/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9820 - loss: 0.0340 - val_accuracy: 0.6884 - val_loss: 1.4530
Epoch 33/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9810 - loss: 0.0339 - val_accuracy: 0.6797 - val_loss: 1.4568
Epoch 34/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9818 - loss: 0.0338 - val_accuracy: 0.6863 - val_loss: 1.4547
Epoch 35/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9825 - loss: 0.0339 - val_accuracy: 0.6838 - val_loss: 1.4664
Epoch 36/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9814 - loss: 0.0334 - val_accuracy: 0.6768 - val_loss: 1.4794
Epoch 37/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9815 - loss: 0.0335 - val_accuracy: 0.6925 - val_loss: 1.4819
Epoch 38/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9810 - loss: 0.0334 - val_accuracy: 0.6843 - val_loss: 1.4885
Epoch 39/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9827 - loss: 0.0332 - val_accuracy: 0.6698 - val_loss: 1.5285
Epoch 40/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9811 - loss: 0.0334 - val_accuracy: 0.6843 - val_loss: 1.5029
Epoch 41/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9821 - loss: 0.0332 - val_accuracy: 0.6822 - val_loss: 1.5123
Epoch 42/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9807 - loss: 0.0333 - val_accuracy: 0.6814 - val_loss: 1.5231
Epoch 43/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9819 - loss: 0.0331 - val_accuracy: 0.6814 - val_loss: 1.5278
Epoch 44/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9820 - loss: 0.0334 - val_accuracy: 0.6801 - val_loss: 1.5435
Epoch 45/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9820 - loss: 0.0331 - val_accuracy: 0.6830 - val_loss: 1.5314
Epoch 46/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9813 - loss: 0.0330 - val_accuracy: 0.6768 - val_loss: 1.5480
Epoch 47/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0328 - val_accuracy: 0.6810 - val_loss: 1.5560
Epoch 48/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9821 - loss: 0.0326 - val_accuracy: 0.6810 - val_loss: 1.5594
Epoch 49/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9824 - loss: 0.0331 - val_accuracy: 0.6843 - val_loss: 1.5683
Epoch 50/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9815 - loss: 0.0327 - val_accuracy: 0.6801 - val_loss: 1.5764
Epoch 51/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9820 - loss: 0.0326 - val_accuracy: 0.6826 - val_loss: 1.5895
Epoch 52/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9819 - loss: 0.0327 - val_accuracy: 0.6785 - val_loss: 1.5969
Epoch 53/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9819 - loss: 0.0324 - val_accuracy: 0.6801 - val_loss: 1.6056
Epoch 54/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0325 - val_accuracy: 0.6785 - val_loss: 1.6210
Epoch 55/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9828 - loss: 0.0322 - val_accuracy: 0.6760 - val_loss: 1.6187
Epoch 56/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9814 - loss: 0.0324 - val_accuracy: 0.6665 - val_loss: 1.6535
Epoch 57/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9823 - loss: 0.0325 - val_accuracy: 0.6801 - val_loss: 1.6342
Epoch 58/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9826 - loss: 0.0324 - val_accuracy: 0.6797 - val_loss: 1.6438
Epoch 59/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9819 - loss: 0.0321 - val_accuracy: 0.6686 - val_loss: 1.6661
Epoch 60/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9822 - loss: 0.0321 - val_accuracy: 0.6739 - val_loss: 1.6625
Epoch 61/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9830 - loss: 0.0321 - val_accuracy: 0.6620 - val_loss: 1.7027
Epoch 62/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9700 - loss: 0.0663 - val_accuracy: 0.6492 - val_loss: 1.5599
Epoch 63/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9607 - loss: 0.0975 - val_accuracy: 0.6690 - val_loss: 1.3911
Epoch 64/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9817 - loss: 0.0363 - val_accuracy: 0.6756 - val_loss: 1.4112
Epoch 65/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9826 - loss: 0.0327 - val_accuracy: 0.6814 - val_loss: 1.4101
Epoch 66/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9827 - loss: 0.0321 - val_accuracy: 0.6810 - val_loss: 1.4216
Epoch 67/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9814 - loss: 0.0322 - val_accuracy: 0.6830 - val_loss: 1.4369
Epoch 68/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0321 - val_accuracy: 0.6834 - val_loss: 1.4493
Epoch 69/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0319 - val_accuracy: 0.6843 - val_loss: 1.4618
Epoch 70/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9831 - loss: 0.0319 - val_accuracy: 0.6834 - val_loss: 1.4710
Epoch 71/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0318 - val_accuracy: 0.6843 - val_loss: 1.4826
Epoch 72/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9820 - loss: 0.0319 - val_accuracy: 0.6810 - val_loss: 1.4923
Epoch 73/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0319 - val_accuracy: 0.6838 - val_loss: 1.4990
Epoch 74/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9827 - loss: 0.0320 - val_accuracy: 0.6830 - val_loss: 1.5094
Epoch 75/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9824 - loss: 0.0318 - val_accuracy: 0.6818 - val_loss: 1.5164
Epoch 76/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9824 - loss: 0.0320 - val_accuracy: 0.6818 - val_loss: 1.5258
Epoch 77/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9822 - loss: 0.0321 - val_accuracy: 0.6814 - val_loss: 1.5371
Epoch 78/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9815 - loss: 0.0321 - val_accuracy: 0.6822 - val_loss: 1.5437
Epoch 79/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9825 - loss: 0.0319 - val_accuracy: 0.6797 - val_loss: 1.5496
Epoch 80/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9826 - loss: 0.0319 - val_accuracy: 0.6826 - val_loss: 1.5522
Epoch 81/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9828 - loss: 0.0318 - val_accuracy: 0.6822 - val_loss: 1.5570
Epoch 82/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9828 - loss: 0.0318 - val_accuracy: 0.6777 - val_loss: 1.5773
Epoch 83/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9821 - loss: 0.0322 - val_accuracy: 0.6797 - val_loss: 1.5744
Epoch 84/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9827 - loss: 0.0317 - val_accuracy: 0.6810 - val_loss: 1.5750
Epoch 85/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9817 - loss: 0.0321 - val_accuracy: 0.6777 - val_loss: 1.5876
Epoch 86/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9825 - loss: 0.0320 - val_accuracy: 0.6715 - val_loss: 1.6039
Epoch 87/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9822 - loss: 0.0318 - val_accuracy: 0.6731 - val_loss: 1.6092
Epoch 88/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9822 - loss: 0.0319 - val_accuracy: 0.6768 - val_loss: 1.6116
Epoch 89/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9827 - loss: 0.0319 - val_accuracy: 0.6772 - val_loss: 1.6144
Epoch 90/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9825 - loss: 0.0318 - val_accuracy: 0.6760 - val_loss: 1.6264
Epoch 91/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9822 - loss: 0.0316 - val_accuracy: 0.6719 - val_loss: 1.6392
Epoch 92/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9826 - loss: 0.0317 - val_accuracy: 0.6744 - val_loss: 1.6329
Epoch 93/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9822 - loss: 0.0318 - val_accuracy: 0.6768 - val_loss: 1.6469
Epoch 94/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9821 - loss: 0.0319 - val_accuracy: 0.6711 - val_loss: 1.6534
Epoch 95/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9823 - loss: 0.0316 - val_accuracy: 0.6702 - val_loss: 1.6724
Epoch 96/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9830 - loss: 0.0316 - val_accuracy: 0.6748 - val_loss: 1.6701
Epoch 97/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9826 - loss: 0.0317 - val_accuracy: 0.6735 - val_loss: 1.6839
Epoch 98/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9820 - loss: 0.0318 - val_accuracy: 0.6748 - val_loss: 1.6881
Epoch 99/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9820 - loss: 0.0315 - val_accuracy: 0.6719 - val_loss: 1.7010
Epoch 100/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9829 - loss: 0.0315 - val_accuracy: 0.6748 - val_loss: 1.7009

In [309]:
import pickle

In [310]:
with open('tokenizer.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)

In [311]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.